import { env } from "@/env";
import { Transcript } from "@/types";

const RE_PATH = /v|e(?:mbed)?|shorts/;
const ID_LENGTH = 11;

/**
 * Get video id from path or search params
 * @param videoUrlOrId - video url or video id
 * @returns {string|null} - the id of null
 */
export const getVideoId = (videoUrlOrId: string): string | null => {
  if (!videoUrlOrId) {
    return null;
  }

  if (videoUrlOrId.length === ID_LENGTH) {
    return videoUrlOrId;
  }

  try {
    const url = new URL(videoUrlOrId);
    const segments = url.pathname.split("/");

    if (segments[1]?.length === ID_LENGTH) {
      return segments[1];
    }

    return (
      (RE_PATH.test(segments[1]) ? segments[2] : url.searchParams.get("v")) ||
      null
    );
  } catch (err) {
    return null;
  }
};

/**
 * Fetch captions for a YouTube video using Apify API
 * @param videoId - The YouTube video ID
 * @returns {Promise<Transcript[]>} Array of transcript segments with text and timestamps
 */
export async function getVideoTranscript(videoId: string): Promise<{
  title: string;
  transcript: Transcript[];
}> {
  try {
    const response = await fetch(
      `https://api.apify.com/v2/acts/streamers~youtube-scraper/run-sync-get-dataset-items?token=${env.APIFY_API_TOKEN}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          startUrls: [
            {
              url: `https://www.youtube.com/watch?v=${videoId}`,
              method: "GET",
            },
          ],
          downloadSubtitles: true,
          saveSubsToKVS: true,
          subtitlesLanguage: "en",
          preferAutoGeneratedSubtitles: true,
          subtitlesFormat: "plaintext",
        }),
      },
    );
    const body = await response.json();
    const video = body[0];
    const { title, subtitles } = video;
    const text = subtitles[0].plaintext;

    if (!response.ok) {
      console.error(response);
      throw new Error(`API request failed with status ${response.status}`);
    }

    // Transform the Apify response into our Transcript format
    const transcript = [
      {
        text,
        start: 0,
      },
    ];
    return {
      title,
      transcript,
    };
  } catch (error) {
    console.error("Failed to fetch transcript:", error);
    throw new Error("Failed to fetch video transcript");
  }
}
